FROM node:22

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG VITE_API_BASE_URL
ARG VITE_NLG_HUB_API_URL
ARG VITE_NLG_HUB_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_NLG_HUB_API_URL=$VITE_NLG_HUB_API_URL
ENV VITE_NLG_HUB_URL=$VITE_NLG_HUB_URL

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
